/*
 * Generated by the Mule project wizard. http://mule.mulesoft.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.module.datapack.config;

import org.mule.config.spring.parsers.generic.ChildDefinitionParser;
import org.mule.config.spring.parsers.specific.MessageProcessorDefinitionParser;
import org.mule.module.datapack.DelimitedToMapsTransformer;
import org.mule.module.datapack.MappingTransformer;
import org.mule.module.datapack.columns.Column;
import org.mule.module.datapack.columns.DateTimeColumn;
import org.mule.module.datapack.columns.TransformColumn;
import org.mule.module.datapack.mapper.DateMapping;
import org.mule.module.datapack.mapper.Mapping;

import org.springframework.beans.factory.xml.NamespaceHandlerSupport;


public class DataPackNamespaceHandler extends NamespaceHandlerSupport
{
    public void init()
    {
        registerBeanDefinitionParser("fixed-width-output-transformer", new FixedWidthOutputDefinitionParser());
        registerBeanDefinitionParser("delimited-output-transformer", new DelimitedOutputDefinitionParser());
        registerBeanDefinitionParser("column", new ChildDefinitionParser("column", Column.class));
        registerBeanDefinitionParser("date-time-column", new ChildDefinitionParser("column",DateTimeColumn.class));
        registerBeanDefinitionParser("transform-column", new ChildDefinitionParser("column", TransformColumn.class));
        registerBeanDefinitionParser("delimited-to-maps-transformer", new MessageProcessorDefinitionParser(DelimitedToMapsTransformer.class));
        registerBeanDefinitionParser("mapping-transformer", new MessageProcessorDefinitionParser(MappingTransformer.class));
        registerBeanDefinitionParser("mapping", new ChildDefinitionParser("mapping", Mapping.class));
        registerBeanDefinitionParser("date-mapping", new ChildDefinitionParser("mapping", DateMapping.class));
    }
}
